using System.Globalization;
using DiskChecker.Core.Interfaces;
using DiskChecker.Core.Models;
using System.Text;

namespace DiskChecker.Core.Services;

public static class CertificateGeneratorExtensions
{
    private static readonly Dictionary<string, Dictionary<string, string>> _translations = new()
    {
        ["cs-CZ"] = new Dictionary<string, string>
        {
            ["app_title"] = "CERTIFIKÁT KONTROLY A TESTU DISKU",
            ["drive_info"] = "IDENTIFIKAČNÍ ÚDAJE DISKU",
            ["smart_params"] = "SMART DATOVÉ PARAMETRY",
            ["test_result"] = "VÝSLEDEK HODNOCENÍ",
            ["warnings"] = "UPOZORNĚNÍ A DOPORUČENÍ",
            ["generated_by"] = "Certifikát vygenerován DiskChecker v0.1",
            ["drive_manufacturer"] = "Výrobce",
            ["drive_model"] = "Model",
            ["serial_number"] = "Sériové číslo",
            ["firmware"] = "Firmware",
            ["power_on_hours"] = "Naběhané hodiny",
            ["reallocated_sectors"] = "Reallocated sectors",
            ["pending_sectors"] = "Pending sectors",
            ["uncorrectable_errors"] = "Uncorrectable errors",
            ["temperature"] = "Teplota",
            ["wear_leveling"] = "Wear leveling",
            ["quality"] = "Kvalita",
            ["summary_a"] = "Výborný stav - disk je vhodný pro další použití",
            ["summary_b"] = "Dobrý stav - minimální riziko problémů",
            ["summary_c"] = "Uspořádaný stav - sledujte parametry",
            ["summary_d"] = "UPOZORNĚNÍ - disk vyžaduje pozornost",
            ["summary_e"] = "KRITICKÝ STAV - brzy může dojít k selhání",
            ["summary_f"] = "SELHÁNÍ - disk nepoužívejte",
            ["summary_unknown"] = "Neznámý stav"
        },
        ["en-US"] = new Dictionary<string, string>
        {
            ["app_title"] = "DISK QUALITY CERTIFICATE",
            ["drive_info"] = "DISK IDENTIFICATION",
            ["smart_params"] = "SMART PARAMETERS",
            ["test_result"] = "TEST RESULT",
            ["warnings"] = "WARNINGS & RECOMMENDATIONS",
            ["generated_by"] = "Certificate generated by DiskChecker v0.1",
            ["drive_manufacturer"] = "Manufacturer",
            ["drive_model"] = "Model",
            ["serial_number"] = "Serial Number",
            ["firmware"] = "Firmware",
            ["power_on_hours"] = "Power On Hours",
            ["reallocated_sectors"] = "Reallocated Sectors",
            ["pending_sectors"] = "Pending Sectors",
            ["uncorrectable_errors"] = "Uncorrectable Errors",
            ["temperature"] = "Temperature",
            ["wear_leveling"] = "Wear Leveling",
            ["quality"] = "Quality",
            ["summary_a"] = "Excellent condition - disk is suitable for continued use",
            ["summary_b"] = "Good condition - minimal risk of problems",
            ["summary_c"] = "Fair condition - monitor parameters",
            ["summary_d"] = "WARNING - disk requires attention",
            ["summary_e"] = "CRITICAL - failure may occur soon",
            ["summary_f"] = "FAILED - do not use this disk",
            ["summary_unknown"] = "Unknown status"
        }
    };

    public static string GenerateCertificate(this QualityRating rating, SmartaData smartaData, DateTime testDate, string lang = "cs-CZ")
    {
        var culture = CultureInfo.GetCultureInfo(lang);
        var t = _translations.GetValueOrDefault(lang, _translations["cs-CZ"]);
        
        var sb = new StringBuilder();
        
        sb.AppendLine(GetLine('='));
        sb.AppendLine(GetCentered(t["app_title"]));
        sb.AppendLine(GetLine('='));
        sb.AppendLine();
        sb.AppendLine($"Date:        {testDate:dd. MM. yyyy HH:mm}");
        sb.AppendLine();
        sb.AppendLine(GetLine('-'));
        sb.AppendLine(GetCentered(t["drive_info"]));
        sb.AppendLine(GetLine('-'));
        sb.AppendLine($"Manufacturer: {smartaData.ModelFamily ?? "Unknown"}");
        sb.AppendLine($"Model:        {smartaData.DeviceModel ?? "Unknown"}");
        sb.AppendLine($"Serial#:      {smartaData.SerialNumber ?? "Unknown"}");
        sb.AppendLine($"Firmware:     {smartaData.FirmwareVersion ?? "Unknown"}");
        sb.AppendLine();
        sb.AppendLine(GetLine('-'));
        sb.AppendLine(GetCentered(t["smart_params"]));
        sb.AppendLine(GetLine('-'));
        sb.AppendLine($"Power On:       {smartaData.PowerOnHours} h");
        sb.AppendLine($"Reallocated:    {smartaData.ReallocatedSectorCount}");
        sb.AppendLine($"Pending:        {smartaData.PendingSectorCount}");
        sb.AppendLine($"Uncorrectable:  {smartaData.UncorrectableErrorCount}");
        sb.AppendLine($"Temperature:    {smartaData.Temperature}°C");
        if (smartaData.WearLevelingCount.HasValue)
        {
            sb.AppendLine($"Wear Leveling:  {smartaData.WearLevelingCount.Value}%");
        }
        sb.AppendLine();
        sb.AppendLine(GetLine('-'));
        sb.AppendLine(GetCentered(t["test_result"]));
        sb.AppendLine(GetLine('-'));
        
        // Use extension methods
        var grade = QualityRatingExtensions.GetGrade(rating);
        var score = QualityRatingExtensions.GetScore(rating);
        var warningCount = QualityRatingExtensions.GetWarnings(rating);
        
        sb.AppendLine($"Grade:         {grade}");
        sb.AppendLine($"Score:         {score:F2}/100");
        sb.AppendLine($"Summary:       {GetSummary(grade, t)}");
        sb.AppendLine();
        
        // Show warnings based on SMART data issues
        var warnings = new List<string>();
        if (smartaData.ReallocatedSectorCount > 0)
            warnings.Add($"Reallocated sectors: {smartaData.ReallocatedSectorCount}");
        if (smartaData.PendingSectorCount > 0)
            warnings.Add($"Pending sectors: {smartaData.PendingSectorCount}");
        if (smartaData.UncorrectableErrorCount > 0)
            warnings.Add($"Uncorrectable errors: {smartaData.UncorrectableErrorCount}");
        if (smartaData.PowerOnHours > 20000)
            warnings.Add($"High power on hours: {smartaData.PowerOnHours} h");
        if (smartaData.Temperature > 50)
            warnings.Add($"High temperature: {smartaData.Temperature}°C");
        
        if (warnings.Count > 0)
        {
            sb.AppendLine(GetLine('-'));
            sb.AppendLine(GetCentered(t["warnings"]));
            sb.AppendLine(GetLine('-'));
            foreach (var warning in warnings)
            {
                sb.AppendLine($"* {warning}");
            }
            sb.AppendLine();
        }
        
        sb.AppendLine(GetLine('='));
        sb.AppendLine(GetCentered(t["generated_by"]));
        sb.AppendLine(GetLine('='));
        
        return sb.ToString();
    }

    private static string GetLine(char c, int length = 63)
    {
        return new string(c, length);
    }

    private static string GetCentered(string text, int length = 63)
    {
        var padding = (length - text.Length) / 2;
        return $"{new string(' ', padding)}{text}{new string(' ', length - text.Length - padding)}";
    }

    private static string GetSummary(QualityGrade grade, Dictionary<string, string> t)
    {
        return grade switch
        {
            QualityGrade.A => t["summary_a"],
            QualityGrade.B => t["summary_b"],
            QualityGrade.C => t["summary_c"],
            QualityGrade.D => t["summary_d"],
            QualityGrade.E => t["summary_e"],
            QualityGrade.F => t["summary_f"],
            _ => t["summary_unknown"]
        };
    }
}
